name: 'Datadog Agent'
description: 'Starts a Datadog Agent and gracefully shuts it down before the job finishes'
inputs:
  container_name:
    description: 'The Datadog Agent container name'
    required: true
    default: 'datadog-agent'
  image_name:
    description: 'The Datadog Agent container image name to use'
    required: true
    default: 'gcr.io/datadoghq/agent'
  api_key:
    description: 'The Datadog API key'
    required: true
  datadog_site:
    description: 'The Datadog site'
    required: true
    default: "datadoghq.com"
  extra_env:
    description: 'A comma separated list of environment variables to pass to the agent'
    required: false
  max_retries:
    description: 'The maximum number of times the action will poll the agent to see if it is ready'
    required: true
    default: '10'
  initial_wait_time:
    description: 'The initial wait time in seconds between polls to see if the agent is ready'
    required: true
    default: '5'
runs:
  using: 'node12'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
