name: 'Datadog Agent'
description: 'Starts a Datadog Agent and gracefully shuts it down before the job finishes'
inputs:
  container_name:
    description: 'The Datadog Agent container name'
    required: true
    default: 'datadog-agent'
  image_name:
    description: 'The Datadog Agent container image name to use'
    required: true
    default: 'gcr.io/datadoghq/agent'
  api_key:
    description: 'The Datadog API key'
    required: true
  datadog_site:
    description: 'The Datadog site'
    required: true
    default: "datadoghq.com"
runs:
  using: 'node12'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
