name: 'Datadog Agent'
description: 'Starts a Datadog Agent for a job and gracefully shut it down before the job finishes'
inputs:
  containerName:
    description: 'The Datadog Agent container name'
    required: true
    default: 'datadog-agent'
  imageName:
    description: 'The Datadog Agent container image name to use'
    required: true
    default: 'gcr.io/datadoghq/agent'
  apiKey:
    description: 'The Datadog API key'
    required: true
  site:
    description: 'The Datadog site'
    required: true
    default: "datadoghq.com"
runs:
  using: 'node12'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
