name: build-on-pr-comments
on:
  issue_comment:
    types:
      - created
jobs:
  rebuild:
    name: Rebuild on PR comment
    # Check it is a PR
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '\build')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: npm install
      - name: Run tests and build
        run: npm run all
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name '${GITHUB_ACTOR}'
          git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
          git commit -am "Rebuild"
          git push