name: Check dependencies license

on: push

jobs:
  check-license-3rdparty:
    name: Check LICENSE-3rdparty.csv
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check LICENSE-3rdparty.csv
        run: ./ci/check-license-3rdparty.sh